# Generated by Django 4.0.2 on 2022-02-14 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='story_author',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
